# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtTesting2.ui',
# licensing of 'QtTesting2.ui' applies.
#
# Created: Tue May  7 11:25:53 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 903)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/Battery3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Image/battery1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(3)
        self.tableWidget_1.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setItem(2, 2, item)
        self.tableWidget_1.horizontalHeader().setDefaultSectionSize(85)
        self.gridLayout_4.addWidget(self.tableWidget_1, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setObjectName("listWidget")
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_LE = QtWidgets.QLineEdit(self.widget_2)
        self.name_LE.setMinimumSize(QtCore.QSize(150, 0))
        self.name_LE.setObjectName("name_LE")
        self.horizontalLayout.addWidget(self.name_LE)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(3000, 200))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.school_LE = QtWidgets.QLineEdit(self.widget_2)
        self.school_LE.setMinimumSize(QtCore.QSize(200, 0))
        self.school_LE.setMaximumSize(QtCore.QSize(150, 16777215))
        self.school_LE.setObjectName("school_LE")
        self.horizontalLayout_3.addWidget(self.school_LE)
        self.school_TB = QtWidgets.QToolButton(self.widget_2)
        self.school_TB.setObjectName("school_TB")
        self.horizontalLayout_3.addWidget(self.school_TB)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(17, 633, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.submit_PB = QtWidgets.QPushButton(self.widget_2)
        self.submit_PB.setMaximumSize(QtCore.QSize(100, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Image/check3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submit_PB.setIcon(icon1)
        self.submit_PB.setObjectName("submit_PB")
        self.horizontalLayout_4.addWidget(self.submit_PB)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Image/Battery2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.tableWidget_1.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.tableWidget_1.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "2", None, -1))
        self.tableWidget_1.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "3", None, -1))
        self.tableWidget_1.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Happy", None, -1))
        self.tableWidget_1.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "New Column", None, -1))
        self.tableWidget_1.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "power", None, -1))
        __sortingEnabled = self.tableWidget_1.isSortingEnabled()
        self.tableWidget_1.setSortingEnabled(False)
        self.tableWidget_1.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "p", None, -1))
        self.tableWidget_1.item(0, 1).setText(QtWidgets.QApplication.translate("MainWindow", "e", None, -1))
        self.tableWidget_1.item(0, 2).setText(QtWidgets.QApplication.translate("MainWindow", "t", None, -1))
        self.tableWidget_1.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "e", None, -1))
        self.tableWidget_1.item(1, 1).setText(QtWidgets.QApplication.translate("MainWindow", "t", None, -1))
        self.tableWidget_1.item(1, 2).setText(QtWidgets.QApplication.translate("MainWindow", "e", None, -1))
        self.tableWidget_1.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "a", None, -1))
        self.tableWidget_1.item(2, 1).setText(QtWidgets.QApplication.translate("MainWindow", "s", None, -1))
        self.tableWidget_1.item(2, 2).setText(QtWidgets.QApplication.translate("MainWindow", "d", None, -1))
        self.tableWidget_1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtWidgets.QApplication.translate("MainWindow", "Python", None, -1))
        self.listWidget.item(1).setText(QtWidgets.QApplication.translate("MainWindow", "Maya", None, -1))
        self.listWidget.item(2).setText(QtWidgets.QApplication.translate("MainWindow", "Nuke", None, -1))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Name:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Gender:", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Male", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Female", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "School:", None, -1))
        self.school_TB.setText(QtWidgets.QApplication.translate("MainWindow", "...", None, -1))
        self.submit_PB.setText(QtWidgets.QApplication.translate("MainWindow", "Submit", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.actionClose.setText(QtWidgets.QApplication.translate("MainWindow", "Close", None, -1))


